services:
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"

  demo:
    build: ./demo
    container_name: demo
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server

  demo2:
    build: ./demo2
    container_name: demo2
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
    
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8083:8080"      # changed from 8081
      - "50000:50000"
    user: root
    volumes:
      - D:\arun:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    restart: unless-stopped

networks:
  jenkins_network:
    driver: bridge
