version: "3.8"
services:
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"

  demo:
    build: ./demo
    container_name: demo
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server

  demo2:
    build: ./demo2
    container_name: demo2
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
